--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: camera_images; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.camera_images (
    id bigint NOT NULL,
    image_url character varying(300),
    video_url character varying(500),
    camera_id bigint
);


ALTER TABLE public.camera_images OWNER TO admin;

--
-- Name: camera_images_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.camera_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.camera_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cameras; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cameras (
    id bigint NOT NULL,
    brand character varying(255),
    description character varying(255),
    model character varying(255),
    price double precision,
    thumbnail character varying(255)
);


ALTER TABLE public.cameras OWNER TO admin;

--
-- Name: cameras_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cameras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cameras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cars; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cars (
    id bigint NOT NULL,
    brand character varying(255),
    color character varying(255),
    model character varying(255),
    price real NOT NULL,
    year integer NOT NULL
);


ALTER TABLE public.cars OWNER TO admin;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cars_images; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cars_images (
    id bigint NOT NULL,
    image_url character varying(300),
    video_url character varying(500),
    car_id bigint
);


ALTER TABLE public.cars_images OWNER TO admin;

--
-- Name: cars_images_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cars_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255),
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['MEMBER'::character varying, 'STAFF'::character varying, 'BREEDER'::character varying, 'MANAGER'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO admin;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(100),
    password character varying(200),
    status character varying(255),
    address character varying(200),
    avatar_url character varying(1024),
    date_of_birth timestamp(6) without time zone,
    first_name character varying(100),
    last_name character varying(100),
    phone_number character varying(20),
    role_id bigint,
    account_balance bigint DEFAULT 0,
    is_active boolean,
    is_subscription boolean
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: camera_images; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.camera_images (id, image_url, video_url, camera_id) FROM stdin;
\.


--
-- Data for Name: cameras; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cameras (id, brand, description, model, price, thumbnail) FROM stdin;
1	Fujifilm	Greate Camera	X100S	10000000	https://photographylife.com/wp-content/uploads/2013/10/Fuji-X100S.jpg
2	Sony	Insane durability	A7iii	70000000	https://cdn.vjshop.vn/may-anh/mirrorless/sony/sony-alpha-a7-mark-iii/sony-alpha-a7-mark-iii.jpg
3	Canon	New generation Technology	R5	50000000	https://cdn.vjshop.vn/may-anh/mirrorless/canon/canon-eos-r5/canon-eos-r5-1-1500x1500.jpg
4	Fujifilm	great	XPro3	70000000	https://cdn.vjshop.vn/may-anh/mirrorless/fujifilm/fujifilm-x-pro3/fujifilm-x-pro3-dura-silver-2000x2000.jpg
5	Canon	durability	6D	8000000	https://mayanh24h.com/upload/assets/catalog/san-pham/may-anh-dslr/canon/canon-eos-6d/canon-6d-cu.jpg
6	Fujifilm	I want this	X100V	50000000	https://bizweb.dktcdn.net/100/107/650/products/fujifilm-x100v-silver-1.jpg?v=1636971415267
\.


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cars (id, brand, color, model, price, year) FROM stdin;
\.


--
-- Data for Name: cars_images; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cars_images (id, image_url, video_url, car_id) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.roles (id, name) FROM stdin;
1	MEMBER
2	STAFF
3	MEMBER
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, created_at, updated_at, email, password, status, address, avatar_url, date_of_birth, first_name, last_name, phone_number, role_id, account_balance, is_active, is_subscription) FROM stdin;
1	2024-10-13 10:20:46.163389	2024-10-13 10:20:46.163404	hoangclw@gmail.com	123	UNVERIFIED	Da Nang, Viet Nam	https://avatars.githubusercontent.com/u/136492579?v=4	\N	Hoang	Luu	0934162561	1	0	t	t
\.


--
-- Name: camera_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.camera_images_id_seq', 1, false);


--
-- Name: cameras_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cameras_id_seq', 6, true);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cars_id_seq', 1, false);


--
-- Name: cars_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cars_images_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.roles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: camera_images camera_images_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.camera_images
    ADD CONSTRAINT camera_images_pkey PRIMARY KEY (id);


--
-- Name: cameras cameras_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cameras
    ADD CONSTRAINT cameras_pkey PRIMARY KEY (id);


--
-- Name: cars_images cars_images_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cars_images
    ADD CONSTRAINT cars_images_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: cars_images fk3lgvnm6pdtqjn03pk2ctan6ll; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cars_images
    ADD CONSTRAINT fk3lgvnm6pdtqjn03pk2ctan6ll FOREIGN KEY (car_id) REFERENCES public.cars(id);


--
-- Name: camera_images fk8yc0r1g91s75yrbru2h2f9ic; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.camera_images
    ADD CONSTRAINT fk8yc0r1g91s75yrbru2h2f9ic FOREIGN KEY (camera_id) REFERENCES public.cameras(id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- PostgreSQL database dump complete
--

